package pl.dakil.healthyshopping.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1E8F4B) // Primary Green
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCF9D9)
val md_theme_light_onPrimaryContainer = Color(0xFF00210C)
val md_theme_light_secondary = Color(0xFF4C6353)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE9D5)
val md_theme_light_onSecondaryContainer = Color(0xFF092013)
val md_theme_light_tertiary = Color(0xFF3B6471)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBFE9F8)
val md_theme_light_onTertiaryContainer = Color(0xFF001F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF8)
val md_theme_light_onSurface = Color(0xFF191C1A)

// Ingredient Highlights - Light
val ingredient_light_green = Color(0xFFCCF9D9)
val ingredient_light_onGreen = Color(0xFF00210C)
val ingredient_light_yellow = Color(0xFFEBF3CC)
val ingredient_light_onYellow = Color(0xFF151D00)
val ingredient_light_orange = Color(0xFFFEEDD9)
val ingredient_light_onOrange = Color(0xFF291800)
val ingredient_light_red = Color(0xFFFFDAD6)
val ingredient_light_onRed = Color(0xFF410002)

val md_theme_dark_primary = Color(0xFF7DDE9C)
val md_theme_dark_onPrimary = Color(0xFF003918)
val md_theme_dark_primaryContainer = Color(0xFF005327)
val md_theme_dark_onPrimaryContainer = Color(0xFFCCF9D9)
val md_theme_dark_secondary = Color(0xFFB3CCB9)
val md_theme_dark_onSecondary = Color(0xFF1F3527)
val md_theme_dark_secondaryContainer = Color(0xFF354B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE9D5)
val md_theme_dark_tertiary = Color(0xFFA3CDDC)
val md_theme_dark_onTertiary = Color(0xFF043542)
val md_theme_dark_tertiaryContainer = Color(0xFF224C59)
val md_theme_dark_onTertiaryContainer = Color(0xFFBFE9F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DF)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DF)

// Ingredient Highlights - Dark
val ingredient_dark_green = Color(0xFF005327)
val ingredient_dark_onGreen = Color(0xFFCCF9D9)
val ingredient_dark_yellow = Color(0xFF3C4B00)
val ingredient_dark_onYellow = Color(0xFFEBF3CC)
val ingredient_dark_orange = Color(0xFF5A3E00)
val ingredient_dark_onOrange = Color(0xFFFEEDD9)
val ingredient_dark_red = Color(0xFF93000A)
val ingredient_dark_onRed = Color(0xFFFFDAD6)

// OLED Theme (True Black Background)
val md_theme_oled_primary = Color(0xFF7DDE9C)
val md_theme_oled_onPrimary = Color(0xFF003918)
val md_theme_oled_primaryContainer = Color(0xFF005327)
val md_theme_oled_onPrimaryContainer = Color(0xFFCCF9D9)
val md_theme_oled_secondary = Color(0xFFB3CCB9)
val md_theme_oled_onSecondary = Color(0xFF1F3527)
val md_theme_oled_secondaryContainer = Color(0xFF354B3C)
val md_theme_oled_onSecondaryContainer = Color(0xFFCEE9D5)
val md_theme_oled_tertiary = Color(0xFFA3CDDC)
val md_theme_oled_onTertiary = Color(0xFF043542)
val md_theme_oled_tertiaryContainer = Color(0xFF224C59)
val md_theme_oled_onTertiaryContainer = Color(0xFFBFE9F8)
val md_theme_oled_error = Color(0xFFFFB4AB)
val md_theme_oled_errorContainer = Color(0xFF93000A)
val md_theme_oled_onError = Color(0xFF690005)
val md_theme_oled_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_oled_background = Color.Black
val md_theme_oled_onBackground = Color(0xFFE1E3DF)
val md_theme_oled_surface = Color.Black
val md_theme_oled_onSurface = Color(0xFFE1E3DF)

// Sepia Theme (Warm brownish/yellow tones)
val md_theme_sepia_primary = Color(0xFF8C5000)
val md_theme_sepia_onPrimary = Color(0xFFFFFFFF)
val md_theme_sepia_primaryContainer = Color(0xFFFFDCBE)
val md_theme_sepia_onPrimaryContainer = Color(0xFF2D1600)
val md_theme_sepia_secondary = Color(0xFF745B45)
val md_theme_sepia_onSecondary = Color(0xFFFFFFFF)
val md_theme_sepia_secondaryContainer = Color(0xFFFFDCBE)
val md_theme_sepia_onSecondaryContainer = Color(0xFF2A1808)
val md_theme_sepia_tertiary = Color(0xFF5A623A)
val md_theme_sepia_onTertiary = Color(0xFFFFFFFF)
val md_theme_sepia_tertiaryContainer = Color(0xFFDEE7B3)
val md_theme_sepia_onTertiaryContainer = Color(0xFF191E00)
val md_theme_sepia_error = Color(0xFFBA1A1A)
val md_theme_sepia_errorContainer = Color(0xFFFFDAD6)
val md_theme_sepia_onError = Color(0xFFFFFFFF)
val md_theme_sepia_onErrorContainer = Color(0xFF410002)
val md_theme_sepia_background = Color(0xFFFBF4EB)
val md_theme_sepia_onBackground = Color(0xFF1F1B16)
val md_theme_sepia_surface = Color(0xFFFBF4EB)
val md_theme_sepia_onSurface = Color(0xFF1F1B16)

// Forest Theme (Deep Green)
val md_theme_forest_primary = Color(0xFF7DDE9C)
val md_theme_forest_onPrimary = Color(0xFF003918)
val md_theme_forest_primaryContainer = Color(0xFF005327)
val md_theme_forest_onPrimaryContainer = Color(0xFFCCF9D9)
val md_theme_forest_secondary = Color(0xFF92F7BB)
val md_theme_forest_onSecondary = Color(0xFF00391E)
val md_theme_forest_secondaryContainer = Color(0xFF00522E)
val md_theme_forest_onSecondaryContainer = Color(0xFFADF3CB)
val md_theme_forest_tertiary = Color(0xFFAAE0C4)
val md_theme_forest_onTertiary = Color(0xFF133725)
val md_theme_forest_tertiaryContainer = Color(0xFF2A4E3B)
val md_theme_forest_onTertiaryContainer = Color(0xFFC5FDE1)
val md_theme_forest_error = Color(0xFFFFB4AB)
val md_theme_forest_errorContainer = Color(0xFF93000A)
val md_theme_forest_onError = Color(0xFF690005)
val md_theme_forest_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_forest_background = Color(0xFF052110)
val md_theme_forest_onBackground = Color(0xFFD4E8DA)
val md_theme_forest_surface = Color(0xFF052110)
val md_theme_forest_onSurface = Color(0xFFD4E8DA)