package pl.dakil.healthyshopping.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1E8F4B) // Primary Green
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCF9D9)
val md_theme_light_onPrimaryContainer = Color(0xFF00210C)
val md_theme_light_secondary = Color(0xFF4C6353)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE9D5)
val md_theme_light_onSecondaryContainer = Color(0xFF092013)
val md_theme_light_tertiary = Color(0xFF3B6471)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBFE9F8)
val md_theme_light_onTertiaryContainer = Color(0xFF001F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF8)
val md_theme_light_onSurface = Color(0xFF191C1A)

val md_theme_dark_primary = Color(0xFF7DDE9C)
val md_theme_dark_onPrimary = Color(0xFF003918)
val md_theme_dark_primaryContainer = Color(0xFF005327)
val md_theme_dark_onPrimaryContainer = Color(0xFFCCF9D9)
val md_theme_dark_secondary = Color(0xFFB3CCB9)
val md_theme_dark_onSecondary = Color(0xFF1F3527)
val md_theme_dark_secondaryContainer = Color(0xFF354B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE9D5)
val md_theme_dark_tertiary = Color(0xFFA3CDDC)
val md_theme_dark_onTertiary = Color(0xFF043542)
val md_theme_dark_tertiaryContainer = Color(0xFF224C59)
val md_theme_dark_onTertiaryContainer = Color(0xFFBFE9F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DF)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DF)